// thin re-export — single truth lives in lib/db.ts
export {
  ensureUsers,
  ensureEvents,
  ensureVerifications,
  ensureMiningLogs,
  ensureCanonicalLog,
  ensureScopeVotes,
  ensureScopeResolution,
  ensureAllTables,
  ensureUsersTable,
  ensureEventsTable,
  ensureVerificationsTable,
  ensureMiningLogsTable,
  ensureMiningTable,
  ensureCanonicalLogTable,
  ensureEventHistoryTable,
  ensureScopeVotes as ensureScopeVotesTable,
  ensureScopeResolution as ensureScopeResolutionTable,
  ensureGhostWitness,
  ensureZkAuthority,
  ensureScopeMiningColumns,
  ensureGhostWitness as ensureGhostWitnessTable,
  ensureZkAuthority as ensureZkAuthorityTable,
  ensureTables,
} from "./db";